Update linting and hooks

diff --git a/.git-hooks/pre-commit b/.git-hooks/pre-commit
--- a/.git-hooks/pre-commit
+++ b/.git-hooks/pre-commit
@@ -1,21 +1,26 @@
 #!/bin/sh
 set -e
 
+# Add yamllint and prettier to PATH
+NVM_BIN=$HOME/.nvm/versions/node/*/bin
+NVM_BIN_PATH=$(echo $NVM_BIN)
+PATH="${HOME}/.local/bin:${NVM_BIN_PATH}:${PATH}"
+
 # Write json version file for README badge
 HA_VER=$(cat .HA_VERSION)
-echo "Setting version ${HA_VER}"
+echo "Setting HA version ${HA_VER}"
 echo "{\"version\":\"${HA_VER}\"}" > .github/version.json
 git add .github/version.json
 
 if ! [ -x "$(command -v prettier)" ]; then
-  echo 'Warning: Prettier is not installed' >&2
+  echo 'Error: Prettier is not installed' && exit 1
 else
   FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.md" "*.yml" "*.yaml" | sed 's| |\\ |g')
   if ! [ -z "$FILES" ]; then
     echo "Running Prettier..."
 
     # Prettify all selected files
-    echo "$FILES" | xargs prettier --write --no-bracket-spacing
+    echo "$FILES" | xargs prettier --write
 
     # Add back the modified/prettified files to staging
     echo "$FILES" | xargs git add
@@ -23,7 +28,7 @@ else
 fi
 
 if ! [ -x "$(command -v yamllint)" ]; then
-  echo 'Warning: yamllint is not installed' >&2
+  echo 'Error: yamllint is not installed' && exit 1
 else
   FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.yml" "*.yaml" | sed 's| |\\ |g')
   if ! [ -z "$FILES" ]; then
